module.exports = {
  pc: require("./ProgramCounter"),
  fork: require("./Fork"),
  adder: require("./Adder"),
  aluctrl: require("./ALUControl"),
  ctrl: require("./Control"),
  alu: require("./ALU"),
  inmem: require("./InstructionMemory"),
  dist: require("./Distributor"),
  mux: require("./MUX"),
  regbank: require("./RegBank"),
  shiftleft: require("./ShiftLeft"),
  signextend: require("./SignExtend"),
  and: require("./And"),
  datamem: require("./DataMemory"),
  or: require("./Or"),
  pipelineregister: require("./PipelineRegister"),
  pipelinecontrol: require("./PipelineControl"),
  pipelinecontrolmux: require("./PipelineControlMux"),
  forwardingunit: require("./ForwardingUnit"),
  hazarddetection: require("./HazardDetection"),
  pipelinemux: require("./PipelineMux"),
};
